-- ZS-FC-001：firstchain 模块 H2 测试库（循 zszj-module-bpm 同名测试基建，与宿主模块 PG DDL 同构）。
-- 不新建任何业务表/迁移（接入合同「不为未来域预建表」+ 本卡硬约束）——仅落既有表的 H2 同构桩：
--   * bpm_first_chain_application / bpm_first_chain_process_binding：ZS-BPM-003 迁移 V20260928.001 的 H2 复制；
--   * audit_event：ZS-AUDIT-001 业务审计表（JdbcAuditPort 落库面）。

-- ZS-BPM-003：首链加盟商申请对象表（M3 三态 DRAFT→SUBMITTED→APPROVED/REJECTED；M8 字段）
CREATE TABLE IF NOT EXISTS "bpm_first_chain_application" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "app_key" varchar(64) NOT NULL,
    "applicant_name" varchar(128) NOT NULL,
    "contact_name" varchar(64),
    "contact_phone" varchar(32),
    "attachment_file_ids" varchar(512),
    "reject_reason" varchar(1024),
    "status" varchar(32) NOT NULL,
    "version" bigint NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_first_chain_app_key" UNIQUE ("tenant_id", "app_key")
) COMMENT ='首链加盟商申请对象表（ZS-BPM-003，D-07 M3 三态）';

-- ZS-BPM-003：首链审批流程实例绑定表（幂等命令门 BOUND→COMPLETED/WITHDRAWN）
CREATE TABLE IF NOT EXISTS "bpm_first_chain_process_binding" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "domain_type" varchar(32) NOT NULL,
    "domain_id" bigint NOT NULL,
    "app_key" varchar(64) NOT NULL,
    "process_instance_id" varchar(64) NOT NULL,
    "outcome" varchar(32),
    "status" varchar(24) NOT NULL,
    "tenant_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_first_chain_binding_pinst" UNIQUE ("process_instance_id")
) COMMENT ='首链审批流程实例绑定表（ZS-BPM-003，幂等命令门）';

-- ZS-AUDIT-001：业务审计事件表（不可改写历史，只追加；tenant_id 可空不默认 0，无 deleted/updater/update_time）
CREATE TABLE IF NOT EXISTS "audit_event" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event_type" varchar(128) NOT NULL,
    "actor_type" varchar(16) NOT NULL,
    "actor_id" varchar(64) DEFAULT NULL,
    "action" varchar(64) DEFAULT NULL,
    "biz_type" varchar(64) DEFAULT NULL,
    "biz_id" varchar(128) DEFAULT NULL,
    "biz_version" varchar(64) DEFAULT NULL,
    "reason" varchar(512) DEFAULT NULL,
    "result" varchar(16) NOT NULL,
    "detail" text DEFAULT NULL,
    "tenant_id" bigint DEFAULT NULL,
    "trace_id" varchar(64) DEFAULT NULL,
    "idempotency_key" varchar(128) DEFAULT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
) COMMENT ='业务审计事件表（ZS-AUDIT-001）';
CREATE UNIQUE INDEX IF NOT EXISTS "uk_audit_event_idempotency" ON "audit_event" ("idempotency_key");

-- ZS-FC-001：system 侧最小桩表（仅供开通服务的 JdbcTemplate 幂等兜底查询与 mock 副作用落库；
-- 真实 DDL/唯一约束归 system 模块迁移，本桩不承载其语义）
CREATE TABLE IF NOT EXISTS "system_organization" (
    "id" bigint NOT NULL,
    "name" varchar(128),
    "code" varchar(64),
    "type" int,
    "parent_id" bigint,
    "leader_user_id" bigint,
    "status" tinyint,
    "tenant_id" bigint NOT NULL,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT ='组织表最小桩（ZS-FC-001 测试：开通幂等 app_key→组织 查询面）';

CREATE TABLE IF NOT EXISTS "system_role" (
    "id" bigint NOT NULL,
    "name" varchar(64),
    "code" varchar(100),
    "tenant_id" bigint NOT NULL,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT ='角色表最小桩（ZS-FC-001 测试：默认角色 create-or-reuse 查询面）';
