-- ZS-FC-002 单元测试建表（H2，循 zszj-module-bpm FirstChainApplicationServiceTest 基建先例）
-- H2 方言：bit 代替 boolean、IDENTITY 主键；部分唯一索引以普通 UNIQUE 近似（H2 表达力登记，循 ZS-BPM-003 P3-6 先例）
-- 依赖 bpm 模块测试建表的说明：本模块测试自建本卡三表，不依赖跨模块 sql。

CREATE TABLE IF NOT EXISTS "bpm_first_chain_lead" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "lead_key" varchar(64) NOT NULL,
    "customer_name" varchar(128),
    "customer_phone" varchar(32),
    "customer_wechat" varchar(64),
    "customer_address" varchar(256),
    "source" varchar(64),
    "org_id" bigint NOT NULL,
    "assignee_user_id" bigint,
    "status" varchar(32) NOT NULL,
    "version" bigint NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_fc_lead_key" UNIQUE ("tenant_id", "lead_key")
);

CREATE TABLE IF NOT EXISTS "bpm_first_chain_followup" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "lead_id" bigint NOT NULL,
    "content" varchar(2048) NOT NULL,
    "next_step" varchar(512),
    "followup_user_id" bigint NOT NULL,
    "followup_time" timestamp NOT NULL,
    "tenant_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "bpm_first_chain_opportunity" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "opp_key" varchar(64) NOT NULL,
    "lead_id" bigint NOT NULL,
    "customer_name" varchar(128),
    "status" varchar(32) NOT NULL,
    "version" bigint NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_fc_opp_key" UNIQUE ("tenant_id", "opp_key"),
    CONSTRAINT "uk_fc_opp_lead" UNIQUE ("lead_id")
);

CREATE TABLE IF NOT EXISTS "audit_event" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event_type" varchar(128) NOT NULL,
    "actor_type" varchar(16) NOT NULL,
    "actor_id" varchar(64) DEFAULT NULL,
    "action" varchar(64) DEFAULT NULL,
    "biz_type" varchar(64) DEFAULT NULL,
    "biz_id" varchar(128) DEFAULT NULL,
    "biz_version" varchar(64) DEFAULT NULL,
    "reason" varchar(512) DEFAULT NULL,
    "result" varchar(16) NOT NULL,
    "detail" text DEFAULT NULL,
    "tenant_id" bigint DEFAULT NULL,
    "trace_id" varchar(64) DEFAULT NULL,
    "idempotency_key" varchar(128) DEFAULT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);
