CREATE TABLE IF NOT EXISTS "bpm_user_group" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "description" varchar(255) NOT NULL,
    "status" tinyint NOT NULL,
    "user_ids" varchar(255) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '用户组';

CREATE TABLE IF NOT EXISTS "bpm_category" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "code" varchar(63) NOT NULL,
    "description" varchar(255) NOT NULL,
    "status" tinyint NOT NULL,
    "sort" int NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '分类';

CREATE TABLE IF NOT EXISTS "bpm_form" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "status" tinyint NOT NULL,
    "fields" varchar(255) NOT NULL,
    "conf" varchar(255) NOT NULL,
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '动态表单';

-- ZS-BPM-004：接入合同样例所依赖的跨模块设施表（H2 schema，与宿主模块 DDL 同构，复制自
-- zszj-module-system/src/test/resources/sql/create_tables.sql）。仅服务本模块测试的「接入合同样例」链路。

-- ZS-AUDIT-001：业务审计事件表（不可改写历史，只追加；tenant_id 可空不默认 0，无 deleted/updater/update_time）
CREATE TABLE IF NOT EXISTS "audit_event" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event_type" varchar(128) NOT NULL,
    "actor_type" varchar(16) NOT NULL,
    "actor_id" varchar(64) DEFAULT NULL,
    "action" varchar(64) DEFAULT NULL,
    "biz_type" varchar(64) DEFAULT NULL,
    "biz_id" varchar(128) DEFAULT NULL,
    "biz_version" varchar(64) DEFAULT NULL,
    "reason" varchar(512) DEFAULT NULL,
    "result" varchar(16) NOT NULL,
    "detail" text DEFAULT NULL,
    "tenant_id" bigint DEFAULT NULL,
    "trace_id" varchar(64) DEFAULT NULL,
    "idempotency_key" varchar(128) DEFAULT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
) COMMENT ='业务审计事件表（ZS-AUDIT-001）';
CREATE UNIQUE INDEX IF NOT EXISTS "uk_audit_event_idempotency" ON "audit_event" ("idempotency_key");

-- ZS-JOB-002：Outbox 事件表（同事务追加 + 租约领取 + 凭证栅栏 + 退避/DEAD）
CREATE TABLE IF NOT EXISTS "outbox_event" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event_type" varchar(128) NOT NULL,
    "biz_type" varchar(64) DEFAULT NULL,
    "biz_id" varchar(128) DEFAULT NULL,
    "biz_version" varchar(64) DEFAULT NULL,
    "payload" text NOT NULL,
    "headers" text DEFAULT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'PENDING' CHECK ("status" IN ('PENDING', 'DISPATCHED', 'DEAD')),
    "retry_count" int NOT NULL DEFAULT 0 CHECK ("retry_count" >= 0),
    "next_retry_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "claimed_by" varchar(128) DEFAULT NULL,
    "claim_token" varchar(64) DEFAULT NULL,
    "claim_expires_at" timestamp DEFAULT NULL,
    "last_error" text DEFAULT NULL,
    "dispatched_at" timestamp DEFAULT NULL,
    "tenant_id" bigint NOT NULL,
    "actor_type" varchar(16) NOT NULL,
    "actor_id" varchar(64) DEFAULT NULL,
    "trace_id" varchar(64) DEFAULT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
) COMMENT ='Outbox 事件表（ZS-JOB-002）';

-- ZS-JOB-003：消费者业务幂等 Inbox 表（处理键唯一抢占、参数指纹冲突、可回查中间态）
CREATE TABLE IF NOT EXISTS "inbox_event" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "consumer" varchar(64) NOT NULL,
    "event_key" varchar(128) NOT NULL,
    "payload_hash" varchar(64) NOT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'PROCESSING' CHECK ("status" IN ('PROCESSING', 'COMPLETED', 'FAILED', 'RESULT_UNKNOWN')),
    "result" text DEFAULT NULL,
    "retry_count" int NOT NULL DEFAULT 0 CHECK ("retry_count" >= 0),
    "biz_type" varchar(64) DEFAULT NULL,
    "biz_id" varchar(128) DEFAULT NULL,
    "biz_version" varchar(64) DEFAULT NULL,
    "last_error" text DEFAULT NULL,
    "tenant_id" bigint NOT NULL,
    "trace_id" varchar(64) DEFAULT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "complete_time" timestamp DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_inbox_event_key" UNIQUE ("tenant_id", "consumer", "event_key")
) COMMENT ='消费者业务幂等 Inbox 表（ZS-JOB-003）';

-- ZS-JOB-003：对象版本水位表（版本乱序护栏的稳定串行化点）
CREATE TABLE IF NOT EXISTS "inbox_object_watermark" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id" bigint NOT NULL,
    "consumer" varchar(64) NOT NULL,
    "biz_type" varchar(64) NOT NULL,
    "biz_id" varchar(128) NOT NULL,
    "version_watermark" bigint NOT NULL DEFAULT 0,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_inbox_object_watermark" UNIQUE ("tenant_id", "consumer", "biz_type", "biz_id")
) COMMENT ='对象版本水位表（ZS-JOB-003）';

-- ZS-MSG-002：业务待办表（通用机制级状态；独立于站内信已读语义）
CREATE TABLE IF NOT EXISTS "system_notify_todo" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "todo_key" varchar(128) NOT NULL,
    "source_type" varchar(32) NOT NULL,
    "biz_type" varchar(64) DEFAULT NULL,
    "biz_id" varchar(128) DEFAULT NULL,
    "biz_version" varchar(64) DEFAULT NULL,
    "title" varchar(256) DEFAULT NULL,
    "message_id" bigint DEFAULT NULL,
    "recipient_type" varchar(16) NOT NULL,
    "recipient_id" bigint NOT NULL,
    "assignee_type" varchar(16) DEFAULT NULL,
    "assignee_id" bigint DEFAULT NULL,
    "status" varchar(24) NOT NULL,
    "status_reason" varchar(512) DEFAULT NULL,
    "todo_version" bigint NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_notify_todo_key" UNIQUE ("tenant_id", "source_type", "todo_key"),
    CONSTRAINT "ck_notify_todo_status" CHECK ("status" IN ('PENDING','COMPLETED','WITHDRAWN','REASSIGNED','INVALID'))
) COMMENT ='业务待办表（ZS-MSG-002）';

-- ZS-BPM-004：中性合同样例对象表（技术语义字段；演示对象归属 + 版本乐观锁，不含任何业务域字段）
CREATE TABLE IF NOT EXISTS "tech_neutral_contract_record" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contract_key" varchar(128) NOT NULL,
    "status" varchar(24) NOT NULL,
    "version" bigint NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_tech_neutral_contract_key" UNIQUE ("tenant_id", "contract_key")
) COMMENT ='中性合同样例对象表（ZS-BPM-004）';

-- ZS-BPM-003：首链领域状态与幂等写回（加盟商申请对象 + 流程实例绑定，D-07 M1/M3/M10）
CREATE TABLE IF NOT EXISTS "bpm_first_chain_application" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "app_key" varchar(64) NOT NULL,
    "applicant_name" varchar(128) NOT NULL,
    "contact_name" varchar(64),
    "contact_phone" varchar(32),
    "attachment_file_ids" varchar(512),
    "reject_reason" varchar(1024),
    "status" varchar(32) NOT NULL,
    "version" bigint NOT NULL DEFAULT 0,
    "tenant_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_first_chain_app_key" UNIQUE ("tenant_id", "app_key")
) COMMENT ='首链加盟商申请对象表（ZS-BPM-003，D-07 M3 三态）';

CREATE TABLE IF NOT EXISTS "bpm_first_chain_process_binding" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "domain_type" varchar(32) NOT NULL,
    "domain_id" bigint NOT NULL,
    "app_key" varchar(64) NOT NULL,
    "process_instance_id" varchar(64) NOT NULL,
    "outcome" varchar(32),
    "status" varchar(24) NOT NULL,
    "tenant_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_first_chain_binding_pinst" UNIQUE ("process_instance_id")
) COMMENT ='首链审批流程实例绑定表（ZS-BPM-003，幂等命令门）';
