
CREATE TABLE IF NOT EXISTS "infra_config" (
    "id" bigint(20) NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "category" varchar(50) NOT NULL,
    "type" tinyint NOT NULL,
    "name" varchar(100) NOT NULL DEFAULT '' COMMENT '名字',
    "config_key" varchar(100) NOT NULL DEFAULT '',
    "value" varchar(500) NOT NULL DEFAULT '',
    "visible" bit NOT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "version" int NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '参数配置表';

CREATE TABLE IF NOT EXISTS "infra_file_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "storage" tinyint NOT NULL,
    "remark" varchar(255),
    "master" bit(1) NOT NULL,
    "config" varchar(4096) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '文件配置表';

CREATE TABLE IF NOT EXISTS "infra_file" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "config_id" bigint NOT NULL,
    "name" varchar(256),
    "path" varchar(512),
    "url" varchar(1024),
    "type" varchar(63) DEFAULT NULL,
    "size" bigint NOT NULL,
    "file_hash" varchar(64) DEFAULT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'PUBLISHED',
    "deleting_time" timestamp DEFAULT NULL, -- ZS-FILE-005.B：删除中间态进入时刻（补偿超时/领取租约）
    "owner_user_id" bigint NOT NULL DEFAULT 0,
    "scope" varchar(16) NOT NULL DEFAULT 'PRIVATE',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY ("id")
) COMMENT '文件表';

CREATE TABLE IF NOT EXISTS "infra_file_upload_credential" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "credential_token" varchar(64) NOT NULL,
    "config_id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "owner_user_id" bigint NOT NULL DEFAULT 0,
    "purpose" varchar(64) NOT NULL DEFAULT '',
    "temp_path" varchar(512) NOT NULL,
    "file_name" varchar(256) NOT NULL,
    "content_type" varchar(128) NOT NULL,
    "declared_size" bigint NOT NULL,
    "scope" varchar(16) NOT NULL DEFAULT 'PRIVATE',
    "status" varchar(16) NOT NULL DEFAULT 'WAITING_UPLOAD',
    "expires_time" timestamp NOT NULL,
    "completed_time" timestamp NULL,
    "file_id" bigint NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "infra_job" (
    "id" bigint(20) NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '任务编号',
    "name" varchar(32) NOT NULL COMMENT '任务名称',
    "status" tinyint(4) NOT NULL COMMENT '任务状态',
    "handler_name" varchar(64) NOT NULL COMMENT '处理器的名字',
    "handler_param" varchar(255) DEFAULT NULL COMMENT '处理器的参数',
    "cron_expression" varchar(32) NOT NULL COMMENT 'CRON 表达式',
    "retry_count" int(11) NOT NULL DEFAULT '0' COMMENT '重试次数',
    "retry_interval" int(11) NOT NULL DEFAULT '0' COMMENT '重试间隔',
    "monitor_timeout" int(11) NOT NULL DEFAULT '0' COMMENT '监控超时时间',
    "creator" varchar(64) DEFAULT '' COMMENT '创建者',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    "updater" varchar(64) DEFAULT '' COMMENT '更新者',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    "deleted" bit NOT NULL DEFAULT FALSE COMMENT '是否删除',
    PRIMARY KEY ("id")
) COMMENT='定时任务表';

CREATE TABLE IF NOT EXISTS "infra_job_log" (
    "id" bigint(20) NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '日志编号',
    "job_id" bigint(20) NOT NULL COMMENT '任务编号',
    "handler_name" varchar(64) NOT NULL COMMENT '处理器的名字',
    "handler_param" varchar(255) DEFAULT NULL COMMENT '处理器的参数',
    "execute_index" tinyint(4) NOT NULL DEFAULT '1' COMMENT '第几次执行',
    "begin_time" datetime NOT NULL COMMENT '开始执行时间',
    "end_time" datetime DEFAULT NULL COMMENT '结束执行时间',
    "duration" int(11) DEFAULT NULL COMMENT '执行时长',
    "status" tinyint(4) NOT NULL COMMENT '任务状态',
    "result" varchar(4000) DEFAULT '' COMMENT '结果数据',
    "creator" varchar(64) DEFAULT '' COMMENT '创建者',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    "updater" varchar(64) DEFAULT '' COMMENT '更新者',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    "deleted" bit(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
    PRIMARY KEY ("id")
)COMMENT='定时任务日志表';

CREATE TABLE IF NOT EXISTS "infra_api_access_log" (
    "id" bigint not null GENERATED BY DEFAULT AS IDENTITY,
    "trace_id" varchar(64) not null default '',
    "user_id" bigint not null default '0',
    "user_type" tinyint not null default '0',
    "application_name" varchar(50) not null,
    "request_method" varchar(16) not null default '',
    "request_url" varchar(255) not null default '',
    "request_params" varchar(8000) not null default '',
    "response_body" varchar(8000) not null default '',
    "user_ip" varchar(50) not null,
    "user_agent" varchar(512) not null,
    `operate_module`           varchar(50)   NOT NULL,
    `operate_name`             varchar(50)   NOT NULL,
    `operate_type`     bigint(4)     NOT NULL DEFAULT '0',
    "begin_time" timestamp not null,
    "end_time" timestamp not null,
    "duration" integer not null,
    "result_code" integer not null default '0',
    "result_msg" varchar(512) default '',
    "creator" varchar(64) default '',
    "create_time" timestamp not null default current_timestamp,
    "updater" varchar(64) default '',
    "update_time" timestamp not null default current_timestamp,
    "deleted" bit not null default false,
    "tenant_id" bigint not null default  '0',
    primary key ("id")
) COMMENT 'API 访问日志表';

CREATE TABLE IF NOT EXISTS "infra_api_error_log" (
    "id" bigint not null GENERATED BY DEFAULT AS IDENTITY,
    "trace_id" varchar(64) not null,
    "user_id" bigint not null default '0',
    "user_type" tinyint not null default '0',
    "application_name" varchar(50) not null,
    "request_method" varchar(16) not null,
    "request_url" varchar(255) not null,
    "request_params" varchar(8000) not null,
    "user_ip" varchar(50) not null,
    "user_agent" varchar(512) not null,
    "exception_time" timestamp not null,
    "exception_name" varchar(128) not null default '',
    "exception_message" clob not null,
    "exception_root_cause_message" clob not null,
    "exception_stack_trace" clob not null,
    "exception_class_name" varchar(512) not null,
    "exception_file_name" varchar(512) not null,
    "exception_method_name" varchar(512) not null,
    "exception_line_number" integer not null,
    "process_status" tinyint not null,
    "process_time" timestamp default null,
    "process_user_id" bigint default '0',
    "creator" varchar(64) default '',
    "create_time" timestamp not null default current_timestamp,
    "updater" varchar(64) default '',
    "update_time" timestamp not null default current_timestamp,
    "deleted" bit not null default false,
    "tenant_id" bigint not null default  '0',
    primary key ("id")
) COMMENT '系统异常日志';

CREATE TABLE IF NOT EXISTS "infra_data_source_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "url" varchar(1024) NOT NULL,
    "username" varchar(255) NOT NULL,
    "password" varchar(255) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '数据源配置表';

CREATE TABLE IF NOT EXISTS "infra_codegen_table" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "data_source_config_id" bigint not null,
    "scene" tinyint not null DEFAULT 1,
    "table_name" varchar(200) NOT NULL,
    "table_comment" varchar(500) NOT NULL,
    "remark" varchar(500) NOT NULL,
    "module_name" varchar(30) NOT NULL,
    "business_name" varchar(30) NOT NULL,
    "class_name" varchar(100) NOT NULL,
    "class_comment" varchar(50) NOT NULL,
    "author" varchar(50) NOT NULL,
    "template_type" tinyint not null DEFAULT 1,
    "front_type" tinyint not null,
    "parent_menu_id" bigint not null,
    "master_table_id" bigint not null,
    "sub_join_column_id" bigint not null,
    "sub_join_many" bit not null,
    "tree_parent_column_id" bigint not null,
    "tree_name_column_id" bigint not null,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '代码生成表定义表';

CREATE TABLE IF NOT EXISTS "infra_codegen_column" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "table_id" bigint not null,
    "column_name" varchar(200) NOT NULL,
    "data_type" varchar(100) NOT NULL,
    "column_comment" varchar(500) NOT NULL,
    "nullable" tinyint not null,
    "primary_key" tinyint not null,
    "ordinal_position" int not null,
    "java_type" varchar(32) NOT NULL,
    "java_field" varchar(64) NOT NULL,
    "dict_type" varchar(200) NOT NULL,
    "example" varchar(64) NOT NULL,
    "create_operation" bit not null,
    "update_operation" bit not null,
    "list_operation" bit not null,
    "list_operation_condition" varchar(32) not null,
    "list_operation_result" bit not null,
    "html_type" varchar(32) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '代码生成表字段定义表';

CREATE TABLE IF NOT EXISTS "infra_config_history" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "config_id" bigint NOT NULL,
    "config_key" varchar(100) NOT NULL,
    "change_type" varchar(16) NOT NULL,
    "old_value" varchar(500),
    "new_value" varchar(500),
    "old_version" int,
    "new_version" int,
    "operator_id" bigint,
    "reason" varchar(255),
    "old_value_redacted" bit NOT NULL DEFAULT FALSE,
    "new_value_redacted" bit NOT NULL DEFAULT FALSE,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '参数配置变更历史表';

-- ZS-JOB-002：事务 Outbox 事件表（业务事务内追加、dispatcher 独立短事务领取；tenant_id 非空必来自上下文，无逻辑删除语义）
CREATE TABLE IF NOT EXISTS "outbox_event" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event_type" varchar(128) NOT NULL,
    "biz_type" varchar(64) DEFAULT NULL,
    "biz_id" varchar(128) DEFAULT NULL,
    "biz_version" varchar(64) DEFAULT NULL,
    "payload" text NOT NULL,
    "headers" text DEFAULT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'PENDING' CHECK ("status" IN ('PENDING', 'DISPATCHED', 'DEAD', 'SKIPPED')),
    "retry_count" int NOT NULL DEFAULT 0 CHECK ("retry_count" >= 0),
    "next_retry_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "claimed_by" varchar(128) DEFAULT NULL,
    "claim_token" varchar(64) DEFAULT NULL,
    "claim_expires_at" timestamp DEFAULT NULL,
    "last_error" text DEFAULT NULL,
    "dispatched_at" timestamp DEFAULT NULL,
    "tenant_id" bigint NOT NULL,
    "actor_type" varchar(16) NOT NULL,
    "actor_id" varchar(64) DEFAULT NULL,
    "trace_id" varchar(64) DEFAULT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
) COMMENT ='Outbox 事件表（ZS-JOB-002）';

-- ZS-JOB-002：dispatcher 实例租约登记表（可观测；事件级抢占由 outbox_event.claim_* 承担）
CREATE TABLE IF NOT EXISTS "dispatcher_lease" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "dispatcher_name" varchar(64) NOT NULL,
    "instance_id" varchar(64) NOT NULL,
    "lease_expires_at" timestamp NOT NULL,
    "heartbeat_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_dispatcher_lease_instance" UNIQUE ("dispatcher_name", "instance_id")
) COMMENT ='Outbox dispatcher 实例租约表（ZS-JOB-002）';

-- ZS-JOB-004：Outbox 人工恢复台账（每次 retry/skip 一行，保留恢复前后关联；不可变事实，只增不改）
CREATE TABLE IF NOT EXISTS "outbox_recovery_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event_id" bigint NOT NULL,
    "action" varchar(16) NOT NULL CHECK ("action" IN ('RETRY', 'SKIP')),
    "reason" varchar(512) NOT NULL CHECK (CHAR_LENGTH("reason") > 0),
    "before_status" varchar(16) NOT NULL,
    "after_status" varchar(16) NOT NULL,
    "before_retry_count" int NOT NULL,
    "manual_retry_seq" int NOT NULL DEFAULT 1,
    "operator_type" varchar(16) NOT NULL,
    "operator_id" varchar(64) DEFAULT NULL,
    "tenant_id" bigint NOT NULL,
    "trace_id" varchar(64) DEFAULT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
) COMMENT ='Outbox 人工恢复台账（ZS-JOB-004）';
CREATE TABLE IF NOT EXISTS "infra_file_delivery_ticket" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ticket_hash" varchar(64) NOT NULL,
    "file_id" bigint NOT NULL,
    "owner_user_id" bigint NOT NULL,
    "purpose" varchar(16) NOT NULL,
    "status" varchar(16) NOT NULL,
    "delivery_session_id" varchar(64),
    "login_session" varchar(128),
    "tenant_id" bigint NOT NULL,
    "expires_time" timestamp NOT NULL,
    "redeem_time" timestamp,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '文件交付票据/下载会话表';

-- ZS-JOB-003：消费者业务幂等 Inbox 表（处理键唯一抢占、参数指纹冲突、版本乱序护栏、可回查中间态）
CREATE TABLE IF NOT EXISTS "inbox_event" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "consumer" varchar(64) NOT NULL,
    "event_key" varchar(128) NOT NULL,
    "payload_hash" varchar(64) NOT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'PROCESSING' CHECK ("status" IN ('PROCESSING', 'COMPLETED', 'FAILED', 'RESULT_UNKNOWN')),
    "result" text DEFAULT NULL,
    "retry_count" int NOT NULL DEFAULT 0 CHECK ("retry_count" >= 0),
    "biz_type" varchar(64) DEFAULT NULL,
    "biz_id" varchar(128) DEFAULT NULL,
    "biz_version" varchar(64) DEFAULT NULL,
    "last_error" text DEFAULT NULL,
    "tenant_id" bigint NOT NULL,
    "trace_id" varchar(64) DEFAULT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "complete_time" timestamp DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_inbox_event_key" UNIQUE ("tenant_id", "consumer", "event_key")
) COMMENT ='消费者业务幂等 Inbox 表（ZS-JOB-003）';

-- ZS-JOB-003：对象版本水位表（版本乱序护栏的稳定串行化点）
CREATE TABLE IF NOT EXISTS "inbox_object_watermark" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id" bigint NOT NULL,
    "consumer" varchar(64) NOT NULL,
    "biz_type" varchar(64) NOT NULL,
    "biz_id" varchar(128) NOT NULL,
    "version_watermark" bigint NOT NULL DEFAULT 0,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_inbox_object_watermark" UNIQUE ("tenant_id", "consumer", "biz_type", "biz_id")
) COMMENT ='对象版本水位表（ZS-JOB-003）';

-- ZS-JOB-001：定时任务租户级执行结果明细表（一次执行汇总为一条 infra_job_log，本表按“执行日志 + 技术租户”逐行展开）
CREATE TABLE IF NOT EXISTS "infra_job_tenant_result" (
    "id" bigint(20) NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '明细编号',
    "job_log_id" bigint(20) NOT NULL COMMENT '执行日志编号',
    "tenant_id" bigint(20) NOT NULL COMMENT '技术租户编号',
    "success" bit(1) NOT NULL DEFAULT FALSE COMMENT '是否执行成功',
    "duration_ms" bigint(20) NOT NULL DEFAULT 0 COMMENT '执行时长，单位：毫秒',
    "result_summary" varchar(512) DEFAULT '' COMMENT '结果摘要（已截断）',
    "error_summary" varchar(512) DEFAULT '' COMMENT '异常摘要（已截断并脱敏）',
    "creator" varchar(64) DEFAULT '' COMMENT '创建者',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    "updater" varchar(64) DEFAULT '' COMMENT '更新者',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    "deleted" bit(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_job_tenant_result" UNIQUE ("job_log_id", "tenant_id")
)COMMENT='定时任务租户级执行结果明细表（ZS-JOB-001）';

-- ZS-SEC-011.B：持久化幂等记录表（幂等键唯一约束并发兜底；INSERT RUNNING → 业务 → markSuccess 与业务同事务提交；
-- 失败按 deleteKeyWhenException 删记录或置 FAILED；无逻辑删除语义）。PG 迁移见 V20260916.101__infra_persistent_idempotent.sql
CREATE TABLE IF NOT EXISTS "infra_persistent_idempotent" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "idempotent_key" varchar(64) NOT NULL,
    "tenant_id" bigint DEFAULT NULL,
    "subject_type" varchar(32) DEFAULT NULL,
    "subject_id" varchar(64) DEFAULT NULL,
    -- codex r1 P2-B：与迁移 V20260916.101 同步——Method.toString() 可超 256，放宽 1024；极端超长由切面 boundActionScope 降级
    "action_scope" varchar(1024) NOT NULL,
    "request_digest" varchar(64) NOT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'RUNNING' CHECK ("status" IN ('RUNNING', 'SUCCESS', 'FAILED')),
    "result_snapshot" text DEFAULT NULL,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "complete_time" timestamp DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_persistent_idempotent_key" UNIQUE ("idempotent_key")
) COMMENT ='持久化幂等记录表（ZS-SEC-011.B）';
CREATE INDEX IF NOT EXISTS "idx_persistent_idempotent_create_time" ON "infra_persistent_idempotent" ("create_time");
