-- V20260905.003：P1C 可靠事件、审计与异步交付平台表
-- 归属：底座 Infra 扩展（zhongshu 包）；业务模块经 ReliableEventPort/AuditPort/DeliveryPort 使用，
-- 禁止直接写这些表。平台工程表允许 IDENTITY 主键（与业务表雪花 ID 约定的差异见 P1C 文档）。

CREATE TABLE outbox_event
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type       VARCHAR(64)  NOT NULL,
    biz_type         VARCHAR(64)  NULL,
    biz_id           VARCHAR(64)  NULL,
    payload          JSONB        NOT NULL,
    headers          JSONB        NULL,
    status           VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    retry_count      INT          NOT NULL DEFAULT 0,
    next_retry_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    claimed_by       VARCHAR(128) NULL,
    claim_expires_at TIMESTAMPTZ  NULL,
    last_error       TEXT         NULL,
    dispatched_at    TIMESTAMPTZ  NULL,
    tenant_id        BIGINT       NOT NULL DEFAULT 0,
    create_time      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_outbox_event_status CHECK (status IN ('PENDING', 'DISPATCHED', 'DEAD'))
);
CREATE INDEX idx_outbox_event_claim ON outbox_event (status, next_retry_at, id);

CREATE TABLE audit_event
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id   VARCHAR(64) NULL,
    action     VARCHAR(64) NOT NULL,
    biz_type   VARCHAR(64) NULL,
    biz_id     VARCHAR(64) NULL,
    result     VARCHAR(16) NOT NULL DEFAULT 'SUCCESS',
    detail     JSONB       NULL,
    tenant_id  BIGINT      NOT NULL DEFAULT 0,
    create_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_audit_event_actor_type CHECK (actor_type IN ('USER', 'ADMIN', 'SYSTEM', 'WORKER')),
    CONSTRAINT ck_audit_event_result CHECK (result IN ('SUCCESS', 'FAILURE', 'DENIED'))
);
CREATE INDEX idx_audit_event_type_time ON audit_event (event_type, create_time);
CREATE INDEX idx_audit_event_biz ON audit_event (biz_type, biz_id);

CREATE TABLE export_job
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type          VARCHAR(64)  NOT NULL,
    requester_type    VARCHAR(16)  NOT NULL DEFAULT 'ADMIN',
    requester_user_id BIGINT       NOT NULL,
    filter_snapshot   JSONB        NULL,
    field_scope       JSONB        NULL,
    status            VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    file_asset_id     VARCHAR(64)  NULL,
    file_sha256       VARCHAR(64)  NULL,
    error             TEXT         NULL,
    expires_at        TIMESTAMPTZ  NULL,
    create_time       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    update_time       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_export_job_status CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'EXPIRED'))
);
CREATE INDEX idx_export_job_requester ON export_job (requester_user_id, create_time);

-- dispatcher 实例租约登记：用于可观测与未来按实例门禁；事件级抢占由 outbox_event.claim_* 列承担
CREATE TABLE dispatcher_lease
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispatcher_name VARCHAR(64)  NOT NULL,
    instance_id     VARCHAR(64)  NOT NULL,
    lease_expires_at TIMESTAMPTZ NOT NULL,
    heartbeat_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    create_time     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_dispatcher_lease_instance UNIQUE (dispatcher_name, instance_id)
);

-- 一次性交付/下载票据：只存 token 的 SHA-256，明文仅签发时返回一次
CREATE TABLE one_time_delivery_ticket
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_hash VARCHAR(64)  NOT NULL,
    purpose     VARCHAR(64)  NOT NULL,
    biz_ref     VARCHAR(128) NOT NULL,
    owner_user_id BIGINT     NULL,
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    expires_at  TIMESTAMPTZ  NOT NULL,
    consumed_at TIMESTAMPTZ  NULL,
    consumer_id VARCHAR(64)  NULL,
    create_time TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_one_time_delivery_ticket_status CHECK (status IN ('ACTIVE', 'CONSUMED', 'EXPIRED', 'REVOKED')),
    CONSTRAINT uk_one_time_delivery_ticket_hash UNIQUE (ticket_hash)
);

CREATE TABLE one_time_download_ticket
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_hash VARCHAR(64)  NOT NULL,
    purpose     VARCHAR(64)  NOT NULL,
    biz_ref     VARCHAR(128) NOT NULL,
    owner_user_id BIGINT     NULL,
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    expires_at  TIMESTAMPTZ  NOT NULL,
    consumed_at TIMESTAMPTZ  NULL,
    consumer_id VARCHAR(64)  NULL,
    create_time TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_one_time_download_ticket_status CHECK (status IN ('ACTIVE', 'CONSUMED', 'EXPIRED', 'REVOKED')),
    CONSTRAINT uk_one_time_download_ticket_hash UNIQUE (ticket_hash)
);
